default_masterdata_update_check_timeout: 3    # 默认MasterData数据源检查更新超时时间（秒）
default_masterdata_download_timeout: 20       # 默认MasterData下载超时时间（秒）
default_rip_asset_download_timeout: 5         # 默认解包资源下载超时时间（秒）
rip_img_cache_max_res: 256*256                # 解包资源图片缓存最大分辨率

# 日服
jp:
  masterdata:
    sources:
      - name: "haruki"   # MaterData数据源名称
        base_url: "https://raw.githubusercontent.com/Team-Haruki/haruki-sekai-master/refs/heads/main/master/"    # MasterData数据源基础URL，最终数据路径会类似: {base_url}cards.json
        version_url: "https://raw.githubusercontent.com/Team-Haruki/haruki-sekai-master/refs/heads/main/versions/current_version.json" # MasterData版本信息URL

  rip:  # 解包资源数据源
    sources:
      - name: "haruki" # 数据源名称，由于各家路径格式不同，程序内置了几个预设的名称对应的路径处理，详见 src/plugins/sekai/asset.py 中的 DEFAULT_URL_MAP_METHODS
        base_url: "https://sekai-assets.haruki.seiunx.com/jp-assets/"  # 数据源基础URL，最终资源路径会类似: {base_url}character/member/res005_no047/card_normal.png
      - name: "haruki"
        base_url: "https://sekai-assets-jp.haruki.seiunx.com"
      - name: "haruki"
        base_url: "https://jp-sekai.assets.haruki.seiunx.com/"
      - name: "haruki"
        base_url: "https://sekai-assets-bdf29c81.seiunx.net/jp-assets/"
      - name: "unipjsk"
        base_url: "https://assets.unipjsk.com/"
      - name: "sekai.best"
        base_url: "https://storage.sekai.best/sekai-jp-assets"
      - name: "xxx"
        base_url: "https://xxx/"
        prefixes: # 指定该数据源仅用于特定前缀
          - "music"

# 国服
cn:
  masterdata:
    sources:
      - name: "haruki"   # MaterData数据源名称
        base_url: "https://raw.githubusercontent.com/Team-Haruki/haruki-sekai-sc-master/refs/heads/main/master/"    # MasterData数据源基础URL，最终数据路径会类似: {base_url}cards.json
        version_url: "https://raw.githubusercontent.com/Team-Haruki/haruki-sekai-sc-master/refs/heads/main/versions/current_version.json" # MasterData版本信息URL

  rip:  # 解包资源数据源
    sources:
      - name: "haruki" # 数据源名称，由于各家路径格式不同，程序内置了几个预设的名称对应的路径处理，详见 src/plugins/sekai/asset.py 中的 DEFAULT_URL_MAP_METHODS
        base_url: "https://sekai-assets.haruki.seiunx.com/cn-assets/"  # 数据源基础URL，最终资源路径会类似: {base_url}character/member/res005_no047/card_normal.png
      - name: "haruki"
        base_url: " https://sekai-assets-bdf29c81.seiunx.net/cn-assets/"
      - name: "sekai.best"
        base_url: "https://storage.sekai.best/sekai-cn-assets"
      - name: "unipjsk"
        base_url: "https://assets.unipjsk.com/"
      - name: "haruki"
        base_url: "https://sekai-assets-jp.haruki.seiunx.com"
      - name: "haruki"
        base_url: "https://jp-sekai.assets.haruki.seiunx.com/"
      - name: "xxx"
        base_url: "https://xxx/"
        prefixes: # 指定该数据源仅用于特定前缀
          - "music"

tw:
  masterdata:
    sources:
      - name: "haruki"   # MaterData数据源名称
        base_url: "https://raw.githubusercontent.com/Team-Haruki/haruki-sekai-tc-master/refs/heads/main/master/"    # MasterData数据源基础URL，最终数据路径会类似: {base_url}cards.json
        version_url: "https://raw.githubusercontent.com/Team-Haruki/haruki-sekai-tc-master/refs/heads/main/versions/current_version.json" # MasterData版本信息URL

  rip:  # 解包资源数据源
    sources:
      - name: "sekai.best"
        base_url: "https://storage.sekai.best/sekai-tw-assets"
      - name: "unipjsk"
        base_url: "https://assets.unipjsk.com/"
      - name: "haruki" # 数据源名称，由于各家路径格式不同，程序内置了几个预设的名称对应的路径处理，详见 src/plugins/sekai/asset.py 中的 DEFAULT_URL_MAP_METHODS
        base_url: "https://sekai-assets.haruki.seiunx.com/jp-assets/"  # 数据源基础URL，最终资源路径会类似: {base_url}character/member/res005_no047/card_normal.png
      - name: "haruki"
        base_url: "https://sekai-assets-jp.haruki.seiunx.com"
      - name: "xxx"
        base_url: "https://xxx/"
        prefixes: # 指定该数据源仅用于特定前缀
          - "music"

kr:
  masterdata:
    sources:
      - name: "haruki"   # MaterData数据源名称
        base_url: "https://raw.githubusercontent.com/Team-Haruki/haruki-sekai-kr-master/refs/heads/main/master/"    # MasterData数据源基础URL，最终数据路径会类似: {base_url}cards.json
        version_url: "https://raw.githubusercontent.com/Team-Haruki/haruki-sekai-kr-master/refs/heads/main/versions/current_version.json" # MasterData版本信息URL

  rip:  # 解包资源数据源
    sources:
      - name: "sekai.best"
        base_url: "https://storage.sekai.best/sekai-kr-assets"
      - name: "unipjsk"
        base_url: "https://assets.unipjsk.com/"
      - name: "haruki" # 数据源名称，由于各家路径格式不同，程序内置了几个预设的名称对应的路径处理，详见 src/plugins/sekai/asset.py 中的 DEFAULT_URL_MAP_METHODS
        base_url: "https://sekai-assets.haruki.seiunx.com/jp-assets/"  # 数据源基础URL，最终资源路径会类似: {base_url}character/member/res005_no047/card_normal.png
      - name: "haruki"
        base_url: "https://sekai-assets-jp.haruki.seiunx.com"
      - name: "xxx"
        base_url: "https://xxx/"
        prefixes: # 指定该数据源仅用于特定前缀
          - "music"

en:
  masterdata:
    sources:
      - name: "haruki"   # MaterData数据源名称
        base_url: "https://raw.githubusercontent.com/Team-Haruki/haruki-sekai-en-master/refs/heads/main/master/"    # MasterData数据源基础URL，最终数据路径会类似: {base_url}cards.json
        version_url: "https://raw.githubusercontent.com/Team-Haruki/haruki-sekai-en-master/refs/heads/main/versions/current_version.json" # MasterData版本信息URL

  rip:  # 解包资源数据源
    sources:
      - name: "sekai.best"
        base_url: "https://storage.sekai.best/sekai-en-assets"
      - name: "unipjsk"
        base_url: "https://assets.unipjsk.com/"
      - name: "haruki" # 数据源名称，由于各家路径格式不同，程序内置了几个预设的名称对应的路径处理，详见 src/plugins/sekai/asset.py 中的 DEFAULT_URL_MAP_METHODS
        base_url: "https://sekai-assets.haruki.seiunx.com/jp-assets/"  # 数据源基础URL，最终资源路径会类似: {base_url}character/member/res005_no047/card_normal.png
      - name: "haruki"
        base_url: "https://sekai-assets-jp.haruki.seiunx.com"
      - name: "xxx"
        base_url: "https://xxx/"
        prefixes: # 指定该数据源仅用于特定前缀
          - "music"