server:
    host: 127.0.0.1
    port: 3939
    suffix: /ws
    bot-id: "548796776"
    user-agent: OneBotFilter
    default:
        private:
            mode: "on"
            ids: []
        group:
            mode: "on"
            ids:
                - 1111111111
                - 66666666
    buffer-size: 4096
    sleep-time: 5
    debug: false
bot-apps:
    - name: sakura
      uri: ws://101.34.19.31:13888/onebot/v11/ws
      access-token: ""
      private:
        mode: blacklist
        ids: []
        message:
            mode: blacklist
            filters:
                - /
                - song
                - 个人信息
                - (?<!pj)sk
                - 时速
                - 逮捕
                - 查卡
                - 查活动
                - 谱面预览
                - cf
                - (?<!pjsk)card
            prefix: []
            prefix-replace: ""
            specific-rules: {}
      group:
        mode: blacklist
        ids:
            - 1234567890
            - 428328396
            - 204235174
            - 1056682350
        message:
            mode: blacklist
            filters:
                - /
                - song
                - 个人信息
                - (?<!pj)sk
                - 时速
                - 逮捕
                - 查卡
                - 查活动
                - 谱面预览
                - cf
                - (?<!pjsk)card
            prefix:
                - b1
                - '#'
            prefix-replace: /
            specific-rules:
                "985432150":
                    filters:
                        - /
                        - song
                        - help
                        - 个人信息
                        - (?<!pj)sk
                        - 时速
                        - 逮捕
                        - 查卡
                        - 查活动
                        - 谱面预览
                        - cf
                        - (?<!pjsk)card
                        - (?i)^\s*pjsk(?!detail\b|card\b|进度\b|b30\b|event\b|听歌识曲\b|猜卡面\b).*
                    prefix:
                        - '!'
                    prefix-replace: ""
                    mode: ""
                "1007019565":
                    filters:
                        - /
                        - song
                        - help
                        - 个人信息
                        - (?<!pj)sk
                        - 时速
                        - 逮捕
                        - 查卡
                        - 查活动
                        - 谱面预览
                        - cf
                        - (?<!pjsk)card
                        - (?i)^\s*pjsk(?!detail\b|card\b|进度\b|b30\b|event\b|听歌识曲\b|猜卡面\b|\d+连\b).*
                        - 啤酒烧烤
                    prefix:
                        - '!'
                    prefix-replace: ""
                    mode: blacklist
                "1030497031":
                    filters: []
                    prefix: []
                    prefix-replace: ""
                    mode: ""
      message:
        mode: ""
        filters: []
        prefix: []
        prefix-replace: ""
        specific-rules: {}
    - name: haruki
      uri: ws://127.0.0.1:3940/ws
      access-token: ""
      private:
        mode: whitelist
        ids: []
        message:
            mode: whitelist
            filters:
                - /
                - pjsk
            prefix:
                - b2
            prefix-replace: ""
            specific-rules: {}
      group:
        mode: blacklist
        ids:
            - 204235174
            - 428328396
            - 1012873802
        message:
            mode: blacklist
            filters: []
            prefix: []
            prefix-replace: ""
            specific-rules: {}
      message:
        mode: ""
        filters: []
        prefix: []
        prefix-replace: ""
        specific-rules: {}
